<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AbilitiesTableSeeder extends Seeder
{
    public function run()
    {
        $abilities = [
            [
                'id' => 1,
                'name' => 'users-manage',
                'title' => 'Users manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 18:09:41',
                'updated_at' => '2021-01-05 18:09:41',
            ],
            [
                'id' => 2,
                'name' => 'users-view',
                'title' => 'None',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:21:55',
                'updated_at' => '2021-01-05 19:25:38',
            ],
            [
                'id' => 3,
                'name' => 'users-create',
                'title' => 'Users create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:26:18',
                'updated_at' => '2021-01-05 19:26:18',
            ],
            [
                'id' => 4,
                'name' => 'users-edit',
                'title' => 'Users edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:26:59',
                'updated_at' => '2021-01-05 19:26:59',
            ],
            [
                'id' => 5,
                'name' => 'users-delete',
                'title' => 'Users delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:27:04',
                'updated_at' => '2021-01-05 19:27:32',
            ],
            [
                'id' => 6,
                'name' => 'roles-manage',
                'title' => 'Roles manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:45:44',
                'updated_at' => '2021-01-05 19:45:44',
            ],
            [
                'id' => 7,
                'name' => 'roles-view',
                'title' => 'Roles view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:46:07',
                'updated_at' => '2021-01-05 19:46:47',
            ],
            [
                'id' => 8,
                'name' => 'roles-create',
                'title' => 'Roles create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:46:32',
                'updated_at' => '2021-01-05 19:46:32',
            ],
            [
                'id' => 9,
                'name' => 'roles-edit',
                'title' => 'Roles edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:47:06',
                'updated_at' => '2021-01-05 19:47:06',
            ],
            [
                'id' => 10,
                'name' => 'roles-delete',
                'title' => 'Roles delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:47:27',
                'updated_at' => '2021-01-05 19:47:27',
            ],
            [
                'id' => 11,
                'name' => 'abilities-manage',
                'title' => 'Abilities manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:48:05',
                'updated_at' => '2021-01-05 19:48:05',
            ],
            [
                'id' => 12,
                'name' => 'abilities-view',
                'title' => 'Abilities view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:48:32',
                'updated_at' => '2021-01-05 19:48:32',
            ],
            [
                'id' => 13,
                'name' => 'abilities-create',
                'title' => 'Abilities create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:53:57',
                'updated_at' => '2021-01-05 22:00:41',
            ],
            [
                'id' => 14,
                'name' => 'abilities-edit',
                'title' => 'Abilities edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:54:39',
                'updated_at' => '2021-01-05 19:54:39',
            ],
            [
                'id' => 15,
                'name' => 'abilities-delete',
                'title' => 'Abilities delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:55:17',
                'updated_at' => '2021-01-05 19:55:17',
            ],
            [
                'id' => 16,
                'name' => 'staffs-manage',
                'title' => 'Staffs manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:55:34',
                'updated_at' => '2021-01-05 19:55:34',
            ],
            [
                'id' => 17,
                'name' => 'staffs-view',
                'title' => 'Staffs view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:55:48',
                'updated_at' => '2021-01-05 19:55:48',
            ],
            [
                'id' => 18,
                'name' => 'staffs-create',
                'title' => 'Staffs create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:56:02',
                'updated_at' => '2021-01-05 19:56:02',
            ],
            [
                'id' => 19,
                'name' => 'staffs-edit',
                'title' => 'Staffs edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:56:25',
                'updated_at' => '2021-01-05 19:56:25',
            ],
            [
                'id' => 20,
                'name' => 'staffs-delete',
                'title' => 'Staffs delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:56:45',
                'updated_at' => '2021-01-05 19:56:45',
            ],
            [
                'id' => 21,
                'name' => 'settings-manage',
                'title' => 'Settings manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 19:58:06',
                'updated_at' => '2021-01-05 19:58:06',
            ],
            [
                'id' => 22,
                'name' => 'institutions-manage',
                'title' => 'Institutions manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:01:16',
                'updated_at' => '2021-01-05 20:01:16',
            ],
            [
                'id' => 23,
                'name' => 'institutions-view',
                'title' => 'Institutions view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:01:33',
                'updated_at' => '2021-01-05 20:01:33',
            ],
            [
                'id' => 24,
                'name' => 'institutions-create',
                'title' => 'Institutions create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:02:10',
                'updated_at' => '2021-01-05 20:02:10',
            ],
            [
                'id' => 25,
                'name' => 'institutions-edit',
                'title' => 'Institutions edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:03:13',
                'updated_at' => '2021-01-05 20:03:13',
            ],
            [
                'id' => 26,
                'name' => 'institutions-delete',
                'title' => 'Institutions delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:04:12',
                'updated_at' => '2021-01-05 20:04:12',
            ],
            [
                'id' => 27,
                'name' => 'campus-manage',
                'title' => 'Campus manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:04:45',
                'updated_at' => '2021-01-05 20:04:45',
            ],
            [
                'id' => 28,
                'name' => 'campus-view',
                'title' => 'Campus view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:05:20',
                'updated_at' => '2021-01-05 20:05:20',
            ],
            [
                'id' => 29,
                'name' => 'campus-create',
                'title' => 'Campus create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:06:09',
                'updated_at' => '2021-01-05 20:06:09',
            ],
            [
                'id' => 30,
                'name' => 'campus-edit',
                'title' => 'Campus edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:06:26',
                'updated_at' => '2021-01-05 20:06:26',
            ],
            [
                'id' => 31,
                'name' => 'campus-delete',
                'title' => 'Campus delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:06:40',
                'updated_at' => '2021-01-05 20:06:40',
            ],
            [
                'id' => 32,
                'name' => 'faculties-manage',
                'title' => 'Faculties manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:08:28',
                'updated_at' => '2021-01-05 20:08:50',
            ],
            [
                'id' => 33,
                'name' => 'faculties-view',
                'title' => 'Faculties view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:09:14',
                'updated_at' => '2021-01-05 20:09:14',
            ],
            [
                'id' => 34,
                'name' => 'faculties-create',
                'title' => 'Faculties create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:09:22',
                'updated_at' => '2021-01-05 20:09:22',
            ],
            [
                'id' => 35,
                'name' => 'faculties-edit',
                'title' => 'Faculties edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:09:34',
                'updated_at' => '2021-01-05 20:09:34',
            ],
            [
                'id' => 36,
                'name' => 'faculties-delete',
                'title' => 'Faculties delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:09:47',
                'updated_at' => '2021-01-05 20:09:47',
            ],
            [
                'id' => 37,
                'name' => 'study_levels-manage',
                'title' => 'Study levels manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 20:09:47',
                'updated_at' => '2021-01-05 20:09:47',
            ],
            [
                'id' => 38,
                'name' => 'study_levels-view',
                'title' => 'Study levels view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:16:02',
                'updated_at' => '2021-01-05 21:16:02',
            ],
            [
                'id' => 39,
                'name' => 'study_levels-create',
                'title' => 'Study levels create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:16:18',
                'updated_at' => '2021-01-05 21:16:18',
            ],
            [
                'id' => 40,
                'name' => 'study_levels-edit',
                'title' => 'Study levels edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:16:36',
                'updated_at' => '2021-01-05 21:16:36',
            ],
            [
                'id' => 41,
                'name' => 'study_levels-delete',
                'title' => 'Study levels delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:16:53',
                'updated_at' => '2021-01-05 21:16:53',
            ],
            [
                'id' => 42,
                'name' => 'intake_categories-manage',
                'title' => 'Intake categories manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:17:45',
                'updated_at' => '2021-01-05 21:17:45',
            ],
            [
                'id' => 43,
                'name' => 'intake_categories-view',
                'title' => 'Intake categories view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:17:57',
                'updated_at' => '2021-01-05 21:17:57',
            ],
            [
                'id' => 44,
                'name' => 'intake_categories-create',
                'title' => 'Intake categories create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:18:12',
                'updated_at' => '2021-01-05 21:18:12',
            ],
            [
                'id' => 45,
                'name' => 'intake_categories-edit',
                'title' => 'Intake categories edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:18:22',
                'updated_at' => '2021-01-05 21:18:22',
            ],
            [
                'id' => 46,
                'name' => 'intake_categories-delete',
                'title' => 'Intake categories delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:18:33',
                'updated_at' => '2021-01-05 21:18:33',
            ],
            [
                'id' => 47,
                'name' => 'semesters-manage',
                'title' => 'Semester manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:18:51',
                'updated_at' => '2021-01-08 15:37:04',
            ],
            [
                'id' => 48,
                'name' => 'semesters-view',
                'title' => 'Semester view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:19:19',
                'updated_at' => '2021-01-08 15:36:50',
            ],
            [
                'id' => 49,
                'name' => 'semesters-create',
                'title' => 'Semester create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:19:33',
                'updated_at' => '2021-01-08 15:36:37',
            ],
            [
                'id' => 50,
                'name' => 'semesters-edit',
                'title' => 'Semester edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:20:01',
                'updated_at' => '2021-01-08 15:36:24',
            ],
            [
                'id' => 51,
                'name' => 'semesters-delete',
                'title' => 'Semester delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:20:22',
                'updated_at' => '2021-01-08 15:36:12',
            ],
            [
                'id' => 52,
                'name' => 'admissions-manage',
                'title' => 'Admission manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:22:19',
                'updated_at' => '2021-01-06 00:01:50',
            ],
            [
                'id' => 53,
                'name' => 'admissions-import_student',
                'title' => 'Admission import student',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:24:09',
                'updated_at' => '2021-01-06 00:01:32',
            ],
            [
                'id' => 54,
                'name' => 'admissions-view',
                'title' => 'Admission class list view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:25:26',
                'updated_at' => '2021-01-06 00:01:14',
            ],
            [
                'id' => 55,
                'name' => 'students-manage',
                'title' => 'Students manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:26:16',
                'updated_at' => '2021-01-05 21:26:16',
            ],
            [
                'id' => 56,
                'name' => 'students-view',
                'title' => 'Students view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:26:54',
                'updated_at' => '2021-01-05 21:26:54',
            ],
            [
                'id' => 57,
                'name' => 'students-edit',
                'title' => 'Students edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:27:11',
                'updated_at' => '2021-01-05 21:27:11',
            ],
            [
                'id' => 58,
                'name' => 'students-delete',
                'title' => 'Students delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:27:24',
                'updated_at' => '2021-01-05 21:27:24',
            ],
            [
                'id' => 59,
                'name' => 'students-restore',
                'title' => 'Students restore',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:27:38',
                'updated_at' => '2021-03-09 16:26:05',
            ],
            [
                'id' => 60,
                'name' => 'programs-manage',
                'title' => 'Programs manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:30:28',
                'updated_at' => '2021-01-05 21:30:28',
            ],
            [
                'id' => 61,
                'name' => 'programs-view',
                'title' => 'Programs view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:30:45',
                'updated_at' => '2021-01-05 21:30:45',
            ],
            [
                'id' => 62,
                'name' => 'programs-create',
                'title' => 'Programs create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:30:59',
                'updated_at' => '2021-01-05 21:30:59',
            ],
            [
                'id' => 63,
                'name' => 'programs-edit',
                'title' => 'Programs edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:31:13',
                'updated_at' => '2021-01-05 21:31:13',
            ],
            [
                'id' => 64,
                'name' => 'programs-delete',
                'title' => 'Programs delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:31:25',
                'updated_at' => '2021-01-05 21:31:25',
            ],
            [
                'id' => 65,
                'name' => 'courses-manage',
                'title' => 'Courses manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:33:17',
                'updated_at' => '2021-01-05 21:33:17',
            ],
            [
                'id' => 66,
                'name' => 'courses-view',
                'title' => 'Courses view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:33:44',
                'updated_at' => '2021-01-05 21:33:44',
            ],
            [
                'id' => 67,
                'name' => 'courses-create',
                'title' => 'Courses create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:34:02',
                'updated_at' => '2021-01-05 21:34:02',
            ],
            [
                'id' => 68,
                'name' => 'courses-edit',
                'title' => 'Courses edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:34:14',
                'updated_at' => '2021-01-05 21:34:14',
            ],
            [
                'id' => 69,
                'name' => 'courses-delete',
                'title' => 'Courses delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:34:37',
                'updated_at' => '2021-01-10 09:28:00',
            ],
            [
                'id' => 70,
                'name' => 'courses-register_core_subjects',
                'title' => 'Courses register core subjects',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 21:36:14',
                'updated_at' => '2021-01-05 21:36:14',
            ],
            [
                'id' => 71,
                'name' => 'staffs-change_year',
                'title' => 'Staffs change year',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:08:35',
                'updated_at' => '2021-01-05 23:08:35',
            ],
            [
                'id' => 72,
                'name' => 'academic_years-manage',
                'title' => 'Academic years manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:44:18',
                'updated_at' => '2021-01-05 23:44:18',
            ],
            [
                'id' => 73,
                'name' => 'academic_years-view',
                'title' => 'Academic years view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:44:31',
                'updated_at' => '2021-01-05 23:44:31',
            ],
            [
                'id' => 74,
                'name' => 'academic_years-create',
                'title' => 'Academic years create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:44:31',
                'updated_at' => '2021-01-05 23:44:31',
            ],
            [
                'id' => 75,
                'name' => 'academic_years-edit',
                'title' => 'Academic years edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:44:58',
                'updated_at' => '2021-01-05 23:44:58',
            ],
            [
                'id' => 76,
                'name' => 'academic_years-delete',
                'title' => 'Academic years delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:45:10',
                'updated_at' => '2021-01-05 23:45:10',
            ],
            [
                'id' => 77,
                'name' => 'sponsors-manage',
                'title' => 'Sponsors manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:49:12',
                'updated_at' => '2021-01-05 23:49:12',
            ],
            [
                'id' => 78,
                'name' => 'sponsors-view',
                'title' => 'Sponsors view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:49:37',
                'updated_at' => '2021-01-05 23:49:37',
            ],
            [
                'id' => 79,
                'name' => 'sponsors-create',
                'title' => 'Sponsors create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:49:50',
                'updated_at' => '2021-01-05 23:49:50',
            ],
            [
                'id' => 80,
                'name' => 'sponsors-edit',
                'title' => 'Sponsors edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:50:02',
                'updated_at' => '2021-01-05 23:50:02',
            ],
            [
                'id' => 81,
                'name' => 'sponsors-delete',
                'title' => 'Sponsors delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:50:12',
                'updated_at' => '2021-01-05 23:50:12',
            ],
            [
                'id' => 82,
                'name' => 'departments-manage',
                'title' => 'Departments manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:53:54',
                'updated_at' => '2021-01-05 23:53:54',
            ],
            [
                'id' => 83,
                'name' => 'departments-view',
                'title' => 'Departments view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:54:03',
                'updated_at' => '2021-01-05 23:54:03',
            ],
            [
                'id' => 84,
                'name' => 'departments-create',
                'title' => 'Departments create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:54:28',
                'updated_at' => '2021-01-05 23:54:42',
            ],
            [
                'id' => 85,
                'name' => 'departments-edit',
                'title' => 'Departments edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:54:52',
                'updated_at' => '2021-01-05 23:54:52',
            ],
            [
                'id' => 86,
                'name' => 'departments-delete',
                'title' => 'Departments delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-05 23:55:01',
                'updated_at' => '2021-01-05 23:55:01',
            ],
            [
                'id' => 87,
                'name' => 'exam-categories-manage',
                'title' => 'Exam categories manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:05:50',
                'updated_at' => '2021-01-06 00:05:50',
            ],
            [
                'id' => 88,
                'name' => 'exam-categories-view',
                'title' => 'Exam categories view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:06:02',
                'updated_at' => '2021-01-06 00:06:02',
            ],
            [
                'id' => 89,
                'name' => 'exam-categories-create',
                'title' => 'Exam categories create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:06:20',
                'updated_at' => '2021-01-06 00:06:20',
            ],
            [
                'id' => 90,
                'name' => 'exam-categories-edit',
                'title' => 'Exam categories edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:06:33',
                'updated_at' => '2021-01-06 00:06:33',
            ],
            [
                'id' => 91,
                'name' => 'exam-categories-delete',
                'title' => 'Exam categories delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:06:47',
                'updated_at' => '2021-01-06 00:06:47',
            ],
            [
                'id' => 92,
                'name' => 'payments-manage',
                'title' => 'Payments manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:09:58',
                'updated_at' => '2021-01-06 00:09:58',
            ],
            [
                'id' => 93,
                'name' => 'payments-view',
                'title' => 'Payments view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:10:21',
                'updated_at' => '2021-01-06 00:10:21',
            ],
            [
                'id' => 94,
                'name' => 'payments-create',
                'title' => 'Payments create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:10:30',
                'updated_at' => '2021-01-06 00:10:30',
            ],
            [
                'id' => 95,
                'name' => 'payments-edit',
                'title' => 'Payments edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:10:39',
                'updated_at' => '2021-01-06 00:10:39',
            ],
            [
                'id' => 96,
                'name' => 'payments-delete',
                'title' => 'Payments delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-06 00:10:49',
                'updated_at' => '2021-01-06 00:10:49',
            ],
            [
                'id' => 97,
                'name' => 'positions-manage',
                'title' => 'Positions manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-07 16:26:16',
                'updated_at' => '2021-01-07 16:26:16',
            ],
            [
                'id' => 98,
                'name' => 'positions-create',
                'title' => 'Positions create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-07 16:26:28',
                'updated_at' => '2021-01-07 16:26:28',
            ],
            [
                'id' => 99,
                'name' => 'positions-view',
                'title' => 'Positions view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-07 16:26:40',
                'updated_at' => '2021-01-07 16:26:40',
            ],
            [
                'id' => 100,
                'name' => 'positions-delete',
                'title' => 'Positions delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-07 16:26:51',
                'updated_at' => '2021-01-07 16:26:51',
            ],
            [
                'id' => 101,
                'name' => 'positions-edit',
                'title' => 'Positions edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-07 16:27:01',
                'updated_at' => '2021-01-07 16:27:01',
            ],
            [
                'id' => 102,
                'name' => 'database-manage',
                'title' => 'Database query',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-08 13:31:31',
                'updated_at' => '2021-01-08 13:31:55',
            ],
            [
                'id' => 103,
                'name' => 'database-query',
                'title' => 'Database query',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-08 13:31:43',
                'updated_at' => '2021-01-08 13:31:43',
            ],
            [
                'id' => 104,
                'name' => 'admissions-search_students',
                'title' => 'Admissions search students',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-10 13:18:44',
                'updated_at' => '2021-01-10 13:18:44',
            ],
            [
                'id' => 105,
                'name' => 'dashboard-view',
                'title' => 'Dashboard view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-11 09:30:28',
                'updated_at' => '2021-01-11 09:30:28',
            ],
            [
                'id' => 106,
                'name' => 'academics-manage',
                'title' => 'Academics manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-11 17:28:36',
                'updated_at' => '2021-01-11 17:28:36',
            ],
            [
                'id' => 107,
                'name' => 'timetable-manage',
                'title' => 'Timetable manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:01:22',
                'updated_at' => '2021-01-12 11:01:22',
            ],
            [
                'id' => 108,
                'name' => 'timetable-create',
                'title' => 'Timetable create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:01:39',
                'updated_at' => '2021-01-12 11:01:39',
            ],
            [
                'id' => 109,
                'name' => 'timetable-view',
                'title' => 'Timetable view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:01:52',
                'updated_at' => '2021-01-12 11:01:52',
            ],
            [
                'id' => 110,
                'name' => 'timetable-edit',
                'title' => 'Timetable edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:02:12',
                'updated_at' => '2021-01-12 11:02:12',
            ],
            [
                'id' => 111,
                'name' => 'timetable-delete',
                'title' => 'Timetable delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:02:12',
                'updated_at' => '2021-01-12 11:02:12',
            ],
            [
                'id' => 112,
                'name' => 'timetable-edit',
                'title' => 'Timetable edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:02:12',
                'updated_at' => '2021-01-12 11:02:12',
            ],
            [
                'id' => 113,
                'name' => 'timetable-delete',
                'title' => 'Timetable delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:02:29',
                'updated_at' => '2021-01-12 11:02:29',
            ],
            [
                'id' => 114,
                'name' => 'administrations-manage',
                'title' => 'Administrations manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:41:18',
                'updated_at' => '2021-01-12 11:41:18',
            ],
            [
                'id' => 115,
                'name' => 'administrations-create',
                'title' => 'Administrations create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:41:27',
                'updated_at' => '2021-01-12 11:41:27',
            ],
            [
                'id' => 116,
                'name' => 'administrations-view',
                'title' => 'Administrations view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:41:38',
                'updated_at' => '2021-01-12 11:41:38',
            ],
            [
                'id' => 117,
                'name' => 'administrations-edit',
                'title' => 'Administrations edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:41:49',
                'updated_at' => '2021-01-12 11:41:49',
            ],
            [
                'id' => 118,
                'name' => 'administrations-delete',
                'title' => 'Administrations delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:43:29',
                'updated_at' => '2021-01-12 11:43:29',
            ],
            [
                'id' => 119,
                'name' => 'examinations-manage',
                'title' => 'Examinations manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:43:42',
                'updated_at' => '2021-01-12 11:43:42',
            ],
            [
                'id' => 120,
                'name' => 'examinations-create',
                'title' => 'Examinations create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:43:51',
                'updated_at' => '2021-01-12 11:43:51',
            ],
            [
                'id' => 121,
                'name' => 'examinations-view',
                'title' => 'Examinations view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:44:01',
                'updated_at' => '2021-01-12 11:44:01',
            ],
            [
                'id' => 122,
                'name' => 'examinations-edit',
                'title' => 'Examinations edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:44:16',
                'updated_at' => '2021-01-12 11:44:16',
            ],
            [
                'id' => 123,
                'name' => 'examinations-delete',
                'title' => 'Examinations delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:44:26',
                'updated_at' => '2021-01-12 11:44:26',
            ],
            [
                'id' => 124,
                'name' => 'examinations-search_student_results',
                'title' => 'Examinations search student results',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:44:33',
                'updated_at' => '2021-01-12 11:44:33',
            ],
            [
                'id' => 125,
                'name' => 'communications-manage',
                'title' => 'Communications manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:44:48',
                'updated_at' => '2021-01-12 11:44:48',
            ],
            [
                'id' => 126,
                'name' => 'communications-create',
                'title' => 'Communications create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:44:58',
                'updated_at' => '2021-01-12 11:44:58',
            ],
            [
                'id' => 127,
                'name' => 'communications-view',
                'title' => 'Communications view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:45:07',
                'updated_at' => '2021-01-12 11:45:07',
            ],
            [
                'id' => 128,
                'name' => 'communications-delete',
                'title' => 'Communications delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:45:17',
                'updated_at' => '2021-01-12 11:45:17',
            ],
            [
                'id' => 129,
                'name' => 'communications-edit',
                'title' => 'Communications edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:45:34',
                'updated_at' => '2021-01-12 11:45:34',
            ],
            [
                'id' => 130,
                'name' => 'e-voting-manage',
                'title' => 'E voting manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:46:10',
                'updated_at' => '2021-01-12 11:46:10',
            ],
            [
                'id' => 131,
                'name' => 'e-voting-create',
                'title' => 'E voting create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:46:20',
                'updated_at' => '2021-01-12 11:46:20',
            ],
            [
                'id' => 132,
                'name' => 'e-voting-view',
                'title' => 'E voting view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:47:46',
                'updated_at' => '2021-01-12 11:47:46',
            ],
            [
                'id' => 133,
                'name' => 'e-voting-edit',
                'title' => 'E voting edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:47:55',
                'updated_at' => '2021-01-12 11:47:55',
            ],
            [
                'id' => 134,
                'name' => 'e-voting-delete',
                'title' => 'E voting delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 11:48:04',
                'updated_at' => '2021-01-12 11:48:04',
            ],
            [
                'id' => 135,
                'name' => 'student_panel-manage',
                'title' => 'Student panel manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-12 21:57:23',
                'updated_at' => '2021-01-12 21:57:23',
            ],
            [
                'id' => 136,
                'name' => 'courses-assign_to_instructor',
                'title' => 'Courses assign to instructor',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-13 00:29:19',
                'updated_at' => '2021-01-13 00:29:19',
            ],
            [
                'id' => 137,
                'name' => 'staffs-profile-manage',
                'title' => 'Staffs profile manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-01-17 11:43:24',
                'updated_at' => '2021-01-17 11:43:24',
            ],
            [
                'id' => 138,
                'name' => 'grades-manage',
                'title' => 'Grades manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:43:26',
                'updated_at' => '2021-02-15 13:43:26',
            ],
            [
                'id' => 139,
                'name' => 'grades-view',
                'title' => 'Grades view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:43:51',
                'updated_at' => '2021-02-15 13:43:51',
            ],
            [
                'id' => 140,
                'name' => 'grades-create',
                'title' => 'Grades create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:44:05',
                'updated_at' => '2021-02-15 13:44:05',
            ],
            [
                'id' => 141,
                'name' => 'grades-edit',
                'title' => 'Grades edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:44:18',
                'updated_at' => '2021-02-15 13:44:18',
            ],
            [
                'id' => 142,
                'name' => 'grades-delete',
                'title' => 'Grades delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:44:32',
                'updated_at' => '2021-02-15 13:44:32',
            ],
            [
                'id' => 143,
                'name' => 'gpa-classifications-manage',
                'title' => 'GPA classifications manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:44:43',
                'updated_at' => '2021-02-15 13:44:43',
            ],
            [
                'id' => 144,
                'name' => 'gpa_classifications-view',
                'title' => 'GPA classifications view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:45:13',
                'updated_at' => '2021-02-15 13:45:13',
            ],
            [
                'id' => 145,
                'name' => 'gpa_classifications-create',
                'title' => 'GPA classifications create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:45:27',
                'updated_at' => '2021-02-15 13:45:27',
            ],
            [
                'id' => 146,
                'name' => 'gpa_classifications-edit',
                'title' => 'GPA classifications edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:45:41',
                'updated_at' => '2021-02-15 13:45:41',
            ],
            [
                'id' => 147,
                'name' => 'gpa_classifications-delete',
                'title' => 'GPA classifications delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:45:57',
                'updated_at' => '2021-02-15 13:45:57',
            ],
            [
                'id' => 148,
                'name' => 'usermanual-view',
                'title' => 'usermanual-view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:45:57',
                'updated_at' => '2021-02-15 13:45:57',
            ],
            [
                'id' => 149,
                'name' => 'usermanual-view',
                'title' => 'User manual view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:46:10',
                'updated_at' => '2021-02-15 13:46:10',
            ],
            [
                'id' => 150,
                'name' => 'usermanual-edit',
                'title' => 'User manual edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:46:25',
                'updated_at' => '2021-02-15 13:46:25',
            ],
            [
                'id' => 151,
                'name' => 'usermanual-delete',
                'title' => 'User manual delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:46:39',
                'updated_at' => '2021-02-15 13:46:39',
            ],
            [
                'id' => 152,
                'name' => 'usermanual-create',
                'title' => 'User manual create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:46:50',
                'updated_at' => '2021-02-15 13:46:50',
            ],
            [
                'id' => 153,
                'name' => 'notifications-manage',
                'title' => 'Notifications manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:47:05',
                'updated_at' => '2021-02-15 13:47:05',
            ],
            [
                'id' => 154,
                'name' => 'notifications-view',
                'title' => 'Notifications view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:47:16',
                'updated_at' => '2021-02-15 13:47:16',
            ],
            [
                'id' => 155,
                'name' => 'notifications-create',
                'title' => 'Notifications create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:47:25',
                'updated_at' => '2021-02-15 13:47:25',
            ],
            [
                'id' => 156,
                'name' => 'notifications-edit',
                'title' => 'Notifications edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:47:35',
                'updated_at' => '2021-02-15 13:47:35',
            ],
            [
                'id' => 157,
                'name' => 'notifications-delete',
                'title' => 'Notifications delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:47:45',
                'updated_at' => '2021-02-15 13:47:45',
            ],
            [
                'id' => 158,
                'name' => 'settings-view',
                'title' => 'Settings view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:48:02',
                'updated_at' => '2021-02-15 13:48:02',
            ],
            [
                'id' => 159,
                'name' => 'settings-edit',
                'title' => 'Settings edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:48:12',
                'updated_at' => '2021-02-15 13:48:12',
            ],
            [
                'id' => 160,
                'name' => 'settings-delete',
                'title' => 'Settings delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:48:22',
                'updated_at' => '2021-02-15 13:48:22',
            ],
            [
                'id' => 161,
                'name' => 'settings-create',
                'title' => 'Settings create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:48:32',
                'updated_at' => '2021-02-15 13:48:32',
            ],
            [
                'id' => 162,
                'name' => 'audit-trail-view',
                'title' => 'Audit trail view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:48:44',
                'updated_at' => '2021-02-15 13:48:44',
            ],
            [
                'id' => 163,
                'name' => 'audit-trail-delete',
                'title' => 'Audit trail delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:48:56',
                'updated_at' => '2021-02-15 13:48:56',
            ],
            [
                'id' => 164,
                'name' => 'audit-trail-edit',
                'title' => 'Audit trail edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:49:06',
                'updated_at' => '2021-02-15 13:49:06',
            ],
            [
                'id' => 165,
                'name' => 'audit-trail-create',
                'title' => 'Audit trail create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:49:18',
                'updated_at' => '2021-02-15 13:49:18',
            ],
            [
                'id' => 166,
                'name' => 'audit-trail-manage',
                'title' => 'Audit trail manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:49:30',
                'updated_at' => '2021-02-15 13:49:30',
            ],
            [
                'id' => 167,
                'name' => 'custom-reports-view',
                'title' => 'Custom reports view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:49:42',
                'updated_at' => '2021-02-15 13:49:42',
            ],
            [
                'id' => 168,
                'name' => 'custom-reports-generate',
                'title' => 'Custom reports generate',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:49:56',
                'updated_at' => '2021-02-15 13:49:56',
            ],
            [
                'id' => 169,
                'name' => 'custom-reports-edit',
                'title' => 'Custom reports edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:50:08',
                'updated_at' => '2021-02-15 13:50:08',
            ],
            [
                'id' => 170,
                'name' => 'custom-reports-delete',
                'title' => 'Custom reports delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:50:18',
                'updated_at' => '2021-02-15 13:50:18',
            ],
            [
                'id' => 171,
                'name' => 'custom-reports-create',
                'title' => 'Custom reports create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:50:30',
                'updated_at' => '2021-02-15 13:50:30',
            ],
            [
                'id' => 172,
                'name' => 'system-settings-view',
                'title' => 'System settings view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:50:42',
                'updated_at' => '2021-02-15 13:50:42',
            ],
            [
                'id' => 173,
                'name' => 'system-settings-edit',
                'title' => 'System settings edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:50:54',
                'updated_at' => '2021-02-15 13:50:54',
            ],
            [
                'id' => 174,
                'name' => 'system-settings-delete',
                'title' => 'System settings delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:51:06',
                'updated_at' => '2021-02-15 13:51:06',
            ],
            [
                'id' => 175,
                'name' => 'system-settings-create',
                'title' => 'System settings create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:51:18',
                'updated_at' => '2021-02-15 13:51:18',
            ],
            [
                'id' => 176,
                'name' => 'system-settings-manage',
                'title' => 'System settings manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:51:30',
                'updated_at' => '2021-02-15 13:51:30',
            ],
            [
                'id' => 177,
                'name' => 'user-management-view',
                'title' => 'User management view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:51:42',
                'updated_at' => '2021-02-15 13:51:42',
            ],
            [
                'id' => 178,
                'name' => 'user-management-edit',
                'title' => 'User management edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:51:53',
                'updated_at' => '2021-02-15 13:51:53',
            ],
            [
                'id' => 179,
                'name' => 'user-management-delete',
                'title' => 'User management delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:52:04',
                'updated_at' => '2021-02-15 13:52:04',
            ],
            [
                'id' => 180,
                'name' => 'user-management-create',
                'title' => 'User management create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:52:15',
                'updated_at' => '2021-02-15 13:52:15',
            ],
            [
                'id' => 181,
                'name' => 'attendance-manage',
                'title' => 'Attendance manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:52:27',
                'updated_at' => '2021-02-15 13:52:27',
            ],
            [
                'id' => 182,
                'name' => 'attendance-view',
                'title' => 'Attendance view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:52:39',
                'updated_at' => '2021-02-15 13:52:39',
            ],
            [
                'id' => 183,
                'name' => 'attendance-create',
                'title' => 'Attendance create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:52:51',
                'updated_at' => '2021-02-15 13:52:51',
            ],
            [
                'id' => 184,
                'name' => 'attendance-edit',
                'title' => 'Attendance edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:53:03',
                'updated_at' => '2021-02-15 13:53:03',
            ],
            [
                'id' => 185,
                'name' => 'attendance-delete',
                'title' => 'Attendance delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:53:03',
                'updated_at' => '2021-02-15 13:53:03',
            ],
            [
                'id' => 186,
                'name' => 'attendance-delete',
                'title' => 'Attendance delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:53:15',
                'updated_at' => '2021-02-15 13:53:15',
            ],
            [
                'id' => 187,
                'name' => 'reports-manage',
                'title' => 'Reports manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:53:27',
                'updated_at' => '2021-02-15 13:53:27',
            ],
            [
                'id' => 188,
                'name' => 'reports-view',
                'title' => 'Reports view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:53:39',
                'updated_at' => '2021-02-15 13:53:39',
            ],
            [
                'id' => 189,
                'name' => 'reports-create',
                'title' => 'Reports create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:53:51',
                'updated_at' => '2021-02-15 13:53:51',
            ],
            [
                'id' => 190,
                'name' => 'reports-edit',
                'title' => 'Reports edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:54:03',
                'updated_at' => '2021-02-15 13:54:03',
            ],
            [
                'id' => 191,
                'name' => 'reports-delete',
                'title' => 'Reports delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2021-02-15 13:54:15',
                'updated_at' => '2021-02-15 13:54:15',
            ],
            [
                'id' => 192,
                'name' => 'debtors-view',
                'title' => 'Debtors view',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2023-11-14 06:10:29',
                'updated_at' => '2023-11-14 06:10:29',
            ],
            [
                'id' => 193,
                'name' => 'debtors-manage',
                'title' => 'Debtors manage',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2023-11-14 06:10:45',
                'updated_at' => '2023-11-14 06:10:45',
            ],
            [
                'id' => 194,
                'name' => 'debtors-create',
                'title' => 'Debtors create',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2023-11-14 06:10:58',
                'updated_at' => '2023-11-14 06:10:58',
            ],
            [
                'id' => 195,
                'name' => 'debtors-edit',
                'title' => 'Debtors edit',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2023-11-14 06:11:10',
                'updated_at' => '2023-11-14 06:11:10',
            ],
            [
                'id' => 196,
                'name' => 'debtors-delete',
                'title' => 'Debtors delete',
                'entity_id' => null,
                'entity_type' => null,
                'only_owned' => 0,
                'options' => null,
                'scope' => null,
                'created_at' => '2023-11-14 06:11:23',
                'updated_at' => '2023-11-14 06:11:23',
            ],
        ];

        DB::table('abilities')->insert($abilities);
    }
}