<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FeeStructuresSeeder extends Seeder
{
    public function run()
    {
        DB::table('fee_structures')->insert([
            [
                'id' => 15,
                'name' => 'Tuition fee (Bachelor of Science with Education)',
                'amount' => 1300000,
                'programme_code' => 'BSED',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-25 15:18:59',
                'updated_at' => '2023-11-16 16:36:47',
                'for_student' => 0,
            ],
            [
                'id' => 17,
                'name' => 'Tuition fee for (BBA, BBS, BAED, BISE, BLI, LLB and BA with or in)',
                'amount' => 1200000,
                'programme_code' => 'BA',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-26 09:34:45',
                'updated_at' => '2023-11-10 14:51:41',
                'for_student' => 0,
            ],
            [
                'id' => 23,
                'name' => 'Tuition fee for (Ordinary Diploma in Medical Laboratory Sciences)',
                'amount' => 2200000,
                'programme_code' => 'ODMLT',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-26 10:03:29',
                'updated_at' => '2023-10-26 10:03:29',
                'for_student' => 0,
            ],
            [
                'id' => 24,
                'name' => 'Tuition fee for (Ordinary Diploma in Science and Laboratory Technology)',
                'amount' => 1200000,
                'programme_code' => 'ODSLT',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-26 10:04:16',
                'updated_at' => '2023-10-26 10:04:16',
                'for_student' => 0,
            ],
            [
                'id' => 25,
                'name' => 'Tuition fee for (DBA, DIBF, DLS, DMLT-U, DPLM, ODA-ECA, ODBA, ODJ)',
                'amount' => 920000,
                'programme_code' => 'DIN',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-26 10:18:24',
                'updated_at' => '2023-10-26 10:18:24',
                'for_student' => 0,
            ],
            [
                'id' => 26,
                'name' => 'Tuition fee for (Certificate in Science and Laboratory Technology)',
                'amount' => 800000,
                'programme_code' => 'CSLT',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-26 10:20:27',
                'updated_at' => '2023-10-26 10:20:27',
                'for_student' => 0,
            ],
            [
                'id' => 27,
                'name' => 'Tuition fee for (BTCA, BTCBA, BTCJ, CIBF, CLS, CPLM)',
                'amount' => 700000,
                'programme_code' => 'CIN',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-26 10:22:10',
                'updated_at' => '2023-10-26 10:22:10',
                'for_student' => 0,
            ],
            [
                'id' => 28,
                'name' => 'Tuition fee for Masters',
                'amount' => 3500000,
                'programme_code' => 'MA',
                'hidden' => 0,
                'amount_type' => 'flexible',
                'currency' => '',
                'payment_type' => '001',
                'created_at' => '2023-10-26 10:23:27',
                'updated_at' => '2023-11-16 11:15:18',
                'for_student' => 0,
            ],
            [
                'id' => 29,
                'name' => 'Students’ Union Fee (Masters)',
                'amount' => 10000,
                'programme_code' => 'MA',
                'hidden' => 0,
                'amount_type' => 'fixed',
                'currency' => '',
                'payment_type' => '008',
                'created_at' => '2023-10-26 10:33:52',
                'updated_at' => '2023-10-26 10:35:40',
                'for_student' => 0,
            ],
            [
                'id' => 30,
                'name' => 'Student Identity Card(Masters)',
                'amount' => 10000,
                'programme_code' => 'MA',
                'hidden' => 0,
                'amount_type' => 'fixed',
                'currency' => '',
                'payment_type' => '009',
                'created_at' => '2023-10-26 10:35:15',
                'updated_at' => '2023-10-26 10:35:15',
                'for_student' => 0,
            ],
            [
                'id' => 31,
                'name' => 'Research (Supervision) Fee for Masters Student only',
                'amount' => 300000,
                'programme_code' => 'MA',
                'hidden' => 0,
                'amount_type' => 'fixed',
                'currency' => '',
                'payment_type' => '007',
                'created_at' => '2023-10-26 10:44:43',
                'updated_at' => '2023-10-26 10:44:43',
                'for_student' => 0,
            ]
        ]);
    }
}
